version: v2
managed:
  enabled: true
  disable:
    - file_option: go_package
      module: buf.build/googleapis/googleapis
    - file_option: go_package
      module: buf.build/grpc-ecosystem/grpc-gateway
    - file_option: go_package
      module: buf.build/bufbuild/protovalidate
    - file_option: go_package
      module: buf.build/envoyproxy/protoc-gen-validate
    - file_option: go_package
      module: buf.build/redpandadata/common
  override:
    - file_option: go_package_prefix
      value: github.com/redpanda-data/console/backend/pkg/protogen
plugins:
  - remote: buf.build/grpc-ecosystem/openapiv2:v2.19.1
    out: proto/gen/openapi
    opt:
      - logtostderr=true
      - allow_merge=true
      - output_format=json
      - disable_service_tags=false
      - omit_enum_default_value=true
      - json_names_for_fields=false
      - use_go_templates=true
      - proto3_optional_nullable=true
      - openapi_naming_strategy=simple
      - disable_default_responses=true
