image:
  tag: master-8fcce39

resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 100m
    memory: 512Mi

console:
  config:
    kafka:
      brokers:
        - bootstrap.mybrokers.com:9092
      clientId: redpanda-console
      sasl:
        enabled: true
        mechanism: SCRAM-SHA-256
        username: console
        # password: set via Helm secret / Env variable
      tls:
        enabled: false
    login:
      google:
        enabled: true
        clientId: redacted.apps.googleusercontent.com
        # clientSecret: set via Helm secret / Env variable
        directory:
          # serviceAccountFilepath: set via Helm secret / Env variable
          targetPrincipal: admin@mycompany.com
    enterprise:
      rbac:
        enabled: true
        roleBindingsFilepath: /etc/console/configs/role-bindings.yaml
  roleBindings:
    - roleName: viewer
      metadata:
        # Metadata properties will be shown in the UI. You can omit it if you want to
        name: Developers
      subjects:
        # You can specify all groups or users from different providers here which shall be bound to the same role
        - kind: group
          provider: Google
          name: engineering@mycompany.com
        - kind: user
          provider: Google
          name: singleuser@mycompany.com
    - roleName: admin
      metadata:
        name: Admin
      subjects:
        - kind: user
          provider: Google
          name: adminperson@mycompany.com

secret:
  create: true
  kafka:
    saslPassword: "redacted"
  enterprise:
    license: "redacted"
  login:
    google:
      clientSecret: "redacted"
      groupsServiceAccount: |
        {
          "type": "service_account",
          "project_id": "redacted",
          "private_key_id": "redacted",
          "private_key": "-----BEGIN PRIVATE KEY-----\nREDACTED\n-----END PRIVATE KEY-----\n",
          "client_email": "redacted@projectid.iam.gserviceaccount.com",
          "client_id": "redacted",
          "auth_uri": "https://accounts.google.com/o/oauth2/auth",
          "token_uri": "https://oauth2.googleapis.com/token",
          "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
          "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/redacted.iam.gserviceaccount.com"
        }
