apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "console.fullname" . }}
  labels:
    {{- include "console.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- tpl (toYaml .Values.console.config) $ | nindent 4 }}
  {{- if .Values.console.roles }}
  roles.yaml: |
    roles:
      {{- tpl (toYaml .Values.console.roles) $ | nindent 6 }}
  {{- end }}

  {{- if .Values.console.roleBindings }}
  role-bindings.yaml: |
    roleBindings:
      {{- tpl (toYaml .Values.console.roleBindings) $ | nindent 6 }}
  {{- end }}