# See: https://github.com/cloudhut/kowl/tree/master/docs/config for reference config files.
kafka:
  brokers:
    - broker:29092
  schemaRegistry:
    enabled: true
    urls: ["http://schema-registry:8081"]

connect:
  enabled: true
  clusters:
    - name: connect
      url: http://connect:8083

# server:
  # listenPort: 8080