###################################################################
# Commented config settings are optional and show the defaults
###################################################################
kafka:
  brokers:
    - broker-0.mycompany.com:19092
    - broker-1.mycompany.com:19092
    - broker-2.mycompany.com:19092
  # clientId: kowl
  # sasl:
  #   enabled: false
  #   useHandshake: true
  #   username:
  #   password: # This can be set via the --kafka.sasl.password flag as well
  #   mechanism: PLAIN # PLAIN, SCRAM-SHA-256, SCRAM-SHA-512 and GSSAPI are supported
  #   gssapi:
  #     authType:
  #     keyTabPath:
  #     kerberosConfigPath:
  #     serviceName:
  #     username:
  #     password: # can be set via the --kafka.sasl.gssapi.password flag as well
  #     realm:
  # tls:
  #   enabled: false
  #   caFilepath:
  #   certFilepath:
  #   keyFilepath:
  #   passphrase: # This can be set via the --kafka.tls.passphrase flag as well
  #   insecureSkipTlsVerify: false
  # schemaRegistry:
  #   enabled: true
  #   urls: [] # Url with scheme is required, e.g. ["http://localhost:8081"]
  #   username: # Basic auth username
  #   password: # Basic auth password
  #   bearerToken:
  #   tls:
  #     caFilepath: # Path to a custom CA file. If not specified the system's / trusted root ca is used.
  # protobuf:
  #   enabled: false
  #   mappings: []
  #     # Map the proto type names for each of your topics. These proto types will be used for deserialization
  #     # - topicName: xy
  #     #   valueProtoType: fake_model.Order # You can specify the proto type for the record key and/or value (just one will work too)
  #     #   keyProtoType: package.Type
#     # Git is where the .proto files come from, in the future there might be additional options
#     git:
#       enabled: false
#       repository:
#         url:
#         branch: (defaults to primary/default branch)
#       # How often Kowl shall pull the repository to look for new files. Set 0 to disable periodic pulls
#       refreshInterval: 1m
#       # Basic Auth
#       # If you want to use GitHub's personal access tokens use `token` as username and pass the token as password
#       basicAuth:
#         enabled: true
#         username: token
#         password: #  This can be set via the via the --owl.topic-documentation.git.basic-auth.password flag as well
#       # SSH Auth
#       # You can either pass the private key file directly via flag or yaml config or refer to a mounted key file
#       ssh:
#         enabled: false
#         username:
#         privateKey: # This can be set via the via the --owl.topic-documentation.git.ssh.private-key flag as well
#         privateKeyFilepath:
#         passphrase: # This can be set via the via the --owl.topic-documentation.git.ssh.passphrase flag as well

# owl:
#   # Config to use for embedded topic documentation, see /docs/features/topic-documentation.md for more details
#   topicDocumentation:
#     enabled: false
#     # Git is where the topic documentation can come from, in the future there might be additional options
#     git:
#       enabled: false
#       repository:
#         url:
#         branch: (defaults to primary/default branch)
#       # How often Kowl shall pull the repository to look for new files. Set 0 to disable periodic pulls
#       refreshInterval: 1m
#       # Basic Auth
#       # If you want to use GitHub's personal access tokens use `token` as username and pass the token as password
#       basicAuth:
#         enabled: true
#         username: token
#         password: #  This can be set via the via the --owl.topic-documentation.git.basic-auth.password flag as well
#       # SSH Auth
#       # You can either pass the private key file directly via flag or yaml config or refer to a mounted key file
#       ssh:
#         enabled: false
#         username:
#         privateKey: # This can be set via the via the --owl.topic-documentation.git.ssh.private-key flag as well
#         privateKeyFilepath:
#         passphrase: # This can be set via the via the --owl.topic-documentation.git.ssh.passphrase flag as well

# server:
#   listenPort: 8080
#   gracefulShutdownTimeout: 30s
#   listenPort: 8080
#   readTimeout: 30s
#   writeTimeout: 30s
#   idleTimeout: 30s
#   compressionLevel: 4
#   basePath: # Sub-path under which kowl is hosted. See 'docs/features/hosting.md' for more information
#   setBasePathFromXForwardedPrefix: true # Whether or not to check the 'X-Forwarded-Prefix' header to (potentially) override 'basePath'
#   stripPrefix: true # Whether or not kowl should strip the prefix internally


# logger:
#   level: info

# Only relevant for developers, who might want to run the frontend separately
# serveFrontend: true

# Prefix for all exported prometheus metrics
# metricsNamespace: kowl

###################################################################
# Below flags are only available in Kowl Business
###################################################################
# companyName: # Used for white labeling in the frontend

cloudHut:
  licenseToken: # This can be set via the --cloudhut.license-token flag as well

login:
  # jwtSecret can be any random password, but it must be the same across all replicas you run. It is used to sign JWTs
  # which are used for user sessions. If you change the JWT secret all users will need to login again.
  jwtSecret: # This can be set via the --login.jwt-secret flag as well
  # At least one Login provider must be enabled
  google:
    enabled: false
    clientId:
    clientSecret: # This can be set via the --login.google.client-secret flag as well
    # Below properties are required if you want to create roleBindings on Google groups instead of users
    # directory:
    #   serviceAccountFilepath:
    #   targetPrincipal:
  github:
    enabled: false
    clientId:
    clientSecret: # This can be set via the --login.github.client-secret flag as well
    # Below properties are required if you want to create roleBindings on GitHub teams instead of users
    # directory:
    #   personalAccessToken: # This can be set via the --login.github.directory.personal-access-token flag as well
  okta:
    enabled: false
    url: # Your organization's URL, e.g.: https://mycompany.okta.com
    clientId:
    clientSecret: # This can be set via the --login.okta.client-secret flag as well
    # Below properties are required if you want to create roleBindings on Okta groups instead of users
    # directory:
    #   apiToken: # This can be set via the --login.okta.directory.api-token flag as well

business:
  rolesFilepath:
  roleBindingsFilepath:
  auditLog:
    enabled: false
    additionalHeaders: []
