serveFrontend: false
kafka:
  brokers: ["localhost:19092"]
  schemaRegistry:
    enabled: true
    urls: ["http://localhost:18081"]
redpanda:
  adminApi:
    enabled: true
    urls: ["http://localhost:19644"]
# connect:
#   enabled: true
#   clusters:
#     - name: local-connect-cluster
#       url: http://connect:18083
#     - name: local-connect-cluster2
#       url: http://connect:18083
server:
  listenPort: 9090
  allowedOrigins: ["http://localhost:3000", "http://localhost:3001"]
  # debug: 
  #   enabled: true
# logger:
#   level: "debug"