
name: Build & Push Docker Image

on:
  push:
    branches:
      - master
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Extract ref/branch name
        shell: bash
        run: echo "##[set-output name=ref;]$(echo ${GITHUB_REF##*/})"
        id: extract_ref

      - name: Set timestamp
        shell: bash
        run: echo "::set-output name=time::$(date +%s)"
        id: set_timestamp

      - name: Login to Quay
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: cloudhut+github_push
          password: ${{ secrets.QUAY_ENCRYPTED_PASS }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            quay.io/cloudhut/kowl
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw,value=master
            type=sha,prefix=master-,format=short
            type=semver,pattern={{raw}},enable=${{ github.event.action == 'published' }}

      # Use Buildx with moby/buildkit to utilize registry caching and more
      # advanced building techniques (e.g. concurrent multistage builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: image=moby/buildkit:v0.9.0,network=host

      - name: Build and push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          build-args: |
            CONSOLE_GIT_SHA=${{ github.sha }}
            CONSOLE_GIT_REF=${{ steps.extract_ref.outputs.ref }}
            BUILD_TIMESTAMP=${{ steps.set_timestamp.outputs.time }}
            BUILT_FROM_PUSH=${{ github.event.action != 'published' }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
